INSERT INTO disciplines (name, area)
SELECT * FROM (VALUES
('Administração de Recursos Materiais', 'Geral'),
('Administração Geral e Pública', 'Geral'),
('AFO, Direito Financeiro e Contabilidade Pública', 'Geral'),
('Análise das Demonstrações Contábeis', 'Geral'),
('Antropologia', 'Geral'),
('Arqueologia', 'Geral'),
('Arquitetura', 'Geral'),
('Arquivologia', 'Geral'),
('Artes e Música', 'Geral'),
('Atualidades e Conhecimentos Gerais', 'Geral'),
('Auditoria Governamental e Controle', 'Geral'),
('Auditoria Privada', 'Geral'),
('Bancos - Atendimento, Vendas, História, etc.', 'Geral'),
('Biblioteconomia', 'Geral'),
('Biologia e Biomedicina', 'Geral'),
('Ciências Atuariais (Atuária)', 'Geral'),
('Ciências Políticas', 'Geral'),
('Ciências Sociais', 'Geral'),
('Comunicação Social', 'Geral'),
('Contabilidade de Custos', 'Geral'),
('Contabilidade de Instituições Financeiras e Atuariais', 'Geral'),
('Contabilidade Geral', 'Geral'),
('Criminalística e Medicina Legal', 'Geral'),
('Criminologia', 'Geral'),
('Defesa Civil', 'Geral'),
('Desenho Técnico e Modelagem da Construção', 'Geral'),
('Design e Artes Gráficas', 'Geral'),
('Direito Administrativo', 'Geral'),
('Direito Agrário', 'Geral'),
('Direito Ambiental', 'Geral'),
('Direito Civil', 'Geral'),
('Direito Constitucional', 'Geral'),
('Direito Constitucional (CF/1988 e Doutrina)', 'Geral'),
('Direito do Consumidor', 'Geral'),
('Direito do Trabalho', 'Geral'),
('Direito Eleitoral', 'Geral'),
('Direito Empresarial', 'Geral'),
('Direito Financeiro', 'Geral'),
('Direito Internacional', 'Geral'),
('Direito Militar', 'Geral'),
('Direito Penal', 'Geral'),
('Direito Penal Militar', 'Geral'),
('Direito Previdenciário', 'Geral'),
('Direito Processual Civil', 'Geral'),
('Direito Processual do Trabalho', 'Geral'),
('Direito Processual Penal', 'Geral'),
('Direito Processual Penal Militar', 'Geral'),
('Direito Tributário', 'Geral'),
('Direitos Humanos', 'Geral'),
('Economia', 'Geral'),
('Educação', 'Geral'),
('Educação Física', 'Geral'),
('Enfermagem', 'Geral'),
('Engenharia Agronômica', 'Geral'),
('Engenharia Ambiental', 'Geral'),
('Engenharia Civil', 'Geral'),
('Engenharia de Segurança do Trabalho', 'Geral'),
('Engenharia Elétrica', 'Geral'),
('Engenharia Mecânica', 'Geral'),
('Estatística', 'Geral'),
('Farmácia', 'Geral'),
('Filosofia', 'Geral'),
('Física', 'Geral'),
('Fisioterapia', 'Geral'),
('Fonoaudiologia', 'Geral'),
('Geografia', 'Geral'),
('História', 'Geral'),
('Informática', 'Geral'),
('Legislação de Trânsito', 'Geral'),
('Legislação Estadual', 'Geral'),
('Legislação Federal', 'Geral'),
('Legislação Municipal', 'Geral'),
('Língua Espanhola', 'Geral'),
('Língua Francesa', 'Geral'),
('Língua Inglesa', 'Geral'),
('Língua Portuguesa', 'Geral'),
('Matemática', 'Geral'),
('Matemática Financeira', 'Geral'),
('Medicina', 'Geral'),
('Medicina Veterinária', 'Geral'),
('Nutrição', 'Geral'),
('Odontologia', 'Geral'),
('Psicologia', 'Geral'),
('Química', 'Geral'),
('Raciocínio Lógico', 'Geral'),
('Redação', 'Geral'),
('Saúde Pública', 'Geral'),
('Serviço Social', 'Geral'),
('Sociologia', 'Geral'),
('Tecnologia da Informação (TI)', 'Geral'),
('Teologia', 'Geral')
) AS v(name, area)
WHERE NOT EXISTS (
    SELECT 1 FROM disciplines d WHERE d.name = v.name
);
