"use server"

import { createClient } from "@/infrastructure/supabase/server"

const DISCIPLINES = [
"Administração de Recursos Materiais",
"Administração Geral e Pública",
"AFO, Direito Financeiro e Contabilidade Pública",
"Análise das Demonstrações Contábeis",
"Antropologia",
"Arqueologia",
"Arquitetura",
"Arquivologia",
"Artes e Música",
"Atualidades e Conhecimentos Gerais",
"Auditoria Governamental e Controle",
"Auditoria Privada",
"Bancos - Atendimento, Vendas, História, etc.",
"Biblioteconomia",
"Biologia e Biomedicina",
"Ciências Atuariais (Atuária)",
"Ciências Políticas",
"Ciências Sociais",
"Comunicação Social",
"Contabilidade de Custos",
"Contabilidade de Instituições Financeiras e Atuariais",
"Contabilidade Geral",
"Criminalística e Medicina Legal",
"Criminologia",
"Defesa Civil",
"Desenho Técnico e Modelagem da Construção",
"Design e Artes Gráficas",
"Direito Administrativo (Doutrina e Leis Federais)",
"Direito Administrativo Estadual e do DF",
"Direito Administrativo Municipal",
"Direito Agrário",
"Direito Ambiental",
"Direito Civil",
"Direito Constitucional (CF/1988 e Doutrina)",
"Direito Constitucional Estadual e Distrital",
"Direito Constitucional Municipal",
"Direito Cultural, Desportivo e da Comunicação",
"Direito da Criança e do Adolescente",
"Direito Digital",
"Direito do Consumidor",
"Direito do Trabalho",
"Direito Econômico",
"Direito Educacional",
"Direito Eleitoral",
"Direito Empresarial (Comercial)",
"Direito Internacional Público e Privado",
"Direito Marítimo, Portuário e Aeronáutico",
"Direito Notarial e Registral",
"Direito Penal",
"Direito Penal Militar",
"Direito Previdenciário",
"Direito Processual Civil",
"Direito Processual do Trabalho",
"Direito Processual Penal",
"Direito Processual Penal Militar",
"Direito Sanitário e Saúde",
"Direitos Humanos",
"Direito Tributário",
"Direito Urbanístico",
"Economia e Finanças Públicas",
"Educação Física",
"Enfermagem",
"Engenharia Aeronáutica",
"Engenharia Agronômica e Agrícola",
"Engenharia Ambiental, Florestal e Sanitária",
"Engenharia Cartográfica e de Agrimensura",
"Engenharia Civil e Auditoria de Obras",
"Engenharia de Produção",
"Engenharia Elétrica e Eletrônica",
"Engenharia Mecânica",
"Engenharia Naval",
"Estatística",
"Ética no Serviço Público",
"Farmácia",
"Filosofia e Teologia",
"Finanças e Conhecimentos Bancários",
"Física",
"Fisioterapia",
"Fonoaudiologia",
"Geografia",
"Geologia e Engenharia de Minas",
"Gestão de Projetos (PMBOK)",
"História",
"Informática",
"Legislação Aduaneira",
"Legislação Civil e Processual Civil Especial",
"Legislação das Casas Legislativas",
"Legislação de Trânsito e Transportes",
"Legislação e Ética Profissional",
"Legislação Específica das Agências Reguladoras",
"Legislação Específica das Defensorias Públicas",
"Legislação Específica das Procuradorias (Advocacias Públicas)",
"Legislação Específica dos Ministérios Públicos",
"Legislação Específica dos Tribunais Estaduais",
"Legislação Específica dos Tribunais Federais",
"Legislação Geral Estadual e do DF",
"Legislação Geral Federal",
"Legislação Geral Municipal",
"Legislação Militar",
"Legislação Penal e Processual Penal Especial",
"Legislação Tributária dos Estados e do Distrito Federal",
"Legislação Tributária dos Municípios",
"Legislação Tributária Federal",
"Libras e Inclusão",
"Língua Espanhola (Espanhol)",
"Língua Francesa (Francês)",
"Língua Inglesa (Inglês)",
"Língua Portuguesa (Português)",
"Línguas Estrangeiras Diversas",
"Literatura Brasileira e Estrangeira",
"Matemática",
"Matemática Financeira",
"Medicina",
"Meteorologia e Astronomia",
"Museologia",
"Nutrição, Gastronomia e Engenharia de Alimentos",
"Oceanografia",
"Odontologia",
"Organização de Eventos",
"Pedagogia",
"Psicologia",
"Química e Engenharia Química",
"Raciocínio Lógico",
"Radiologia",
"Redação Oficial",
"Relações Internacionais e Comércio Internacional",
"Secretariado e Taquigrafia",
"Segurança e Proteção Contra Incêndios",
"Segurança e Saúde no Trabalho (SST)",
"Segurança Privada e Transportes",
"Segurança Pública e Legislação Policial",
"Serviços Gerais",
"Serviço Social",
"Teoria Geral, Filosofia e Sociologia Jurídica",
"Terapia Ocupacional",
"TI - Banco de Dados",
"TI - Ciência de Dados e Inteligência Artificial",
"TI - Desenvolvimento de Sistemas",
"TI - Engenharia de Software",
"TI - Gestão e Governança de TI",
"TI - Organização e Arquitetura dos Computadores",
"TI - Redes de Computadores",
"TI - Segurança da Informação",
"TI - Sistemas Operacionais",
"Turismo",
"Veterinária e Zootecnia"
]

export async function seedDisciplinesAction() {
  try {
    const supabase = await createClient()
    
    // Check if user is authenticated (might be required for RLS)
    await supabase.auth.getUser()
    
    const toInsert = DISCIPLINES.map(name => ({
      name,
      area: "Geral"
    }))

    // Use upsert or just insert ignoring duplicates if constraint exists
    for (const item of toInsert) {
      const { data } = await supabase.from("disciplines").select("id").eq("name", item.name).maybeSingle()
      if (!data) {
        await supabase.from("disciplines").insert(item)
      }
    }

    return { success: true }
  } catch (err: unknown) {
    return { success: false, error: err instanceof Error ? err.message : "Unknown error" }
  }
}
