"use client"

import React from "react"

export interface DailyMessage {
  id: string
  text: string
  author: string
  category:
    | "Disciplina"
    | "Constância"
    | "Motivação"
    | "Foco"
    | "Resiliência"
    | "Planejamento"
    | "Concurso"
}

export const DAILY_MESSAGES: DailyMessage[] = [
  { id: "msg-1", text: "Não precisa estar com vontade. Precisa começar.", author: "Anônimo", category: "Motivação" },
  { id: "msg-2", text: "Cinco minutos. Depois você decide se continua.", author: "Anônimo", category: "Motivação" },
  { id: "msg-3", text: "O difícil é sentar. O resto vem.", author: "Anônimo", category: "Motivação" },
  { id: "msg-4", text: "Feito é melhor que perfeito.", author: "Anônimo", category: "Motivação" },
  { id: "msg-5", text: "Comece pela parte mais fácil.", author: "Anônimo", category: "Motivação" },
  { id: "msg-6", text: "Você não precisa de motivação, precisa de rotina.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-7", text: "A vontade aparece depois que você começa, não antes.", author: "Anônimo", category: "Motivação" },
  { id: "msg-8", text: "Hoje pode ser um dia ruim de estudo. Ruim ainda conta.", author: "Anônimo", category: "Constância" },
  { id: "msg-9", text: "Se você espera por motivação para agir, vai viver à mercê do acaso. Mas se age com disciplina, cria seu próprio destino.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-10", text: "Você nunca vai se arrepender de ter estudado. Mas vai se arrepender, sim, de ter desistido quando era difícil.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-11", text: "O que você faz quando não tem vontade é o que define até onde você vai chegar.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-12", text: "Não espere a motivação chegar. Comece sem ela e ela virá.", author: "Anônimo", category: "Motivação" },
  { id: "msg-13", text: "A ação vence a dúvida.", author: "Anônimo", category: "Motivação" },
  { id: "msg-14", text: "Menos desculpas, mais foco.", author: "Anônimo", category: "Foco" },
  { id: "msg-15", text: "A primeira razão para o fracasso de alguém é escutar amigos, família e vizinhos.", author: "Anônimo", category: "Foco" },
  { id: "msg-16", text: "A única coisa que separa você do seu sucesso são as desculpas que você dá para não fazer as coisas.", author: "Anônimo", category: "Foco" },
  { id: "msg-17", text: "O que você faz quando não tem vontade é o que define até onde você vai chegar.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-18", text: "Quem quer fazer um jeito arruma. Quem não quer, arruma desculpa.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-19", text: "Não espere as condições ideais, elas nunca chegam.", author: "Anônimo", category: "Foco" },
  { id: "msg-20", text: "O custo de estar errado é menor do que o custo de não fazer nada.", author: "Seth Godin", category: "Motivação" },
  { id: "msg-21", text: "A melhor maneira de aprender seja o que for é fazendo.", author: "Anônimo", category: "Constância" },
  { id: "msg-22", text: "Estudar é um ato de resistência. Em um mundo que te distrai o tempo inteiro, focar é revolucionário.", author: "Anônimo", category: "Foco" },
  { id: "msg-23", text: "Não há um homem vivo que não possa fazer mais do que ele pensa que pode.", author: "Anônimo", category: "Motivação" },
  { id: "msg-24", text: "Quer você acredite que consiga fazer uma coisa ou não, você está certo.", author: "Henry Ford", category: "Motivação" },
  { id: "msg-25", text: "Acredite que você pode, assim você já está no meio do caminho.", author: "Anônimo", category: "Motivação" },
  { id: "msg-26", text: "Você já está mais perto do que estava ontem.", author: "Anônimo", category: "Constância" },
  { id: "msg-27", text: "Ninguém aprende tudo de uma vez. Ninguém.", author: "Anônimo", category: "Constância" },
  { id: "msg-28", text: "Desanimar faz parte. Parar é que não precisa.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-29", text: "O cansaço passa. O que você aprendeu fica.", author: "Anônimo", category: "Constância" },
  { id: "msg-30", text: "Não compare seu capítulo 3 com o capítulo 20 de outra pessoa.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-31", text: "Um dia ruim não apaga três meses bons.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-32", text: "Estudar cansado é normal. Não é sinal de que você não serve para isso.", author: "Anônimo", category: "Constância" },
  { id: "msg-33", text: "Volte amanhã. Só não desapareça.", author: "Anônimo", category: "Constância" },
  { id: "msg-34", text: "A dor que você sente hoje é a força que você sentirá amanhã.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-35", text: "Enquanto você duvida, alguém está realizando. Enquanto você dorme, alguém está lutando.", author: "Anônimo", category: "Foco" },
  { id: "msg-36", text: "Desistir não é opção quando você já sabe do que é capaz.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-37", text: "Crescer dói. Mas ficar no mesmo lugar dói para sempre.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-38", text: "O preço da disciplina será sempre menor que o do arrependimento.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-39", text: "O seu esforço de hoje será o seu descanso de amanhã.", author: "Anônimo", category: "Constância" },
  { id: "msg-40", text: "Não deixe que o ontem atrapalhe o amanhã.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-41", text: "O fracasso é a oportunidade de começar de novo com mais inteligência.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-42", text: "Muitas das falhas da vida ocorrem quando não percebemos o quão próximos estávamos do sucesso na hora em que desistimos.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-43", text: "Quando a queda dói, é porque a subida foi alta.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-44", text: "Erga a cabeça, sacode a poeira e dá a volta por cima.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-45", text: "O esforço de hoje é o resultado de amanhã.", author: "Anônimo", category: "Constância" },
  { id: "msg-46", text: "Recomeçar não é fracasso, é coragem.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-47", text: "Transforme frustração em combustível.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-48", text: "Cada dia ruim é temporário, continue.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-49", text: "O que os outros pensam de você é problema deles. Faça por você, mesmo que ninguém esteja vendo.", author: "Anônimo", category: "Foco" },
  { id: "msg-50", text: "Não se cobre tanto por algo que você ainda está aprendendo.", author: "Anônimo", category: "Constância" },
  { id: "msg-51", text: "A disciplina é o que sobra quando a motivação acaba.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-52", text: "Estude no horário, não no humor.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-53", text: "Pequeno e diário vence grande e raro.", author: "Anônimo", category: "Constância" },
  { id: "msg-54", text: "Não quebre a corrente duas vezes seguidas.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-55", text: "Uma hora hoje vale mais que seis no domingo.", author: "Anônimo", category: "Planejamento" },
  { id: "msg-56", text: "Planeje o suficiente para começar, não o suficiente para adiar.", author: "Anônimo", category: "Planejamento" },
  { id: "msg-57", text: "O cronograma serve a você, não o contrário.", author: "Anônimo", category: "Planejamento" },
  { id: "msg-58", text: "Comece agora, o resto vem com hábito.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-59", text: "Um dia de cada vez, uma página por vez.", author: "Anônimo", category: "Constância" },
  { id: "msg-60", text: "Pequenos passos geram grandes conquistas.", author: "Anônimo", category: "Constância" },
  { id: "msg-61", text: "Persistência transforma esforço em resultado.", author: "Anônimo", category: "Constância" },
  { id: "msg-62", text: "Estudar hoje é investir no amanhã.", author: "Anônimo", category: "Constância" },
  { id: "msg-63", text: "O progresso é melhor que a perfeição.", author: "Anônimo", category: "Constância" },
  { id: "msg-64", text: "Disciplina é liberdade em construção.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-65", text: "Crie uma rotina e honre-a todos os dias.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-66", text: "A consistência é o segredo do sucesso nos estudos.", author: "Anônimo", category: "Constância" },
  { id: "msg-67", text: "Reserve um horário sagrado para aprender.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-68", text: "Comece pelo mais difícil e ganhe confiança.", author: "Anônimo", category: "Foco" },
  { id: "msg-69", text: "Transforme a curiosidade em hábito de estudo.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-70", text: "Cada revisão fixa o conhecimento.", author: "Anônimo", category: "Constância" },
  { id: "msg-71", text: "Use metas pequenas e mensuráveis.", author: "Anônimo", category: "Planejamento" },
  { id: "msg-72", text: "A prática diária constrói competência.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-73", text: "Você se torna o que repete. Não o que deseja, não o que sonha — mas o que faz, dia após dia.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-74", text: "Resultados extraordinários vêm de ações ordinárias feitas com consistência inabalável.", author: "Anônimo", category: "Constância" },
  { id: "msg-75", text: "Repetição não é fracasso. É a fundação invisível do sucesso.", author: "Anônimo", category: "Constância" },
  { id: "msg-76", text: "A disciplina molda seu caráter nos bastidores — para que o mundo aplauda seu desempenho no palco.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-77", text: "Elimine distrações antes de começar.", author: "Anônimo", category: "Foco" },
  { id: "msg-78", text: "Técnicas de Pomodoro aumentam a produtividade.", author: "Anônimo", category: "Foco" },
  { id: "msg-79", text: "Estabeleça prazos curtos e cumpra-os.", author: "Anônimo", category: "Planejamento" },
  { id: "msg-80", text: "Organize seu material para otimizar o tempo.", author: "Anônimo", category: "Planejamento" },
  { id: "msg-81", text: "Não construa links, construa relacionamentos.", author: "Anônimo", category: "Concurso" },
  { id: "msg-82", text: "Decidir o que não fazer é tão importante quanto decidir o que fazer.", author: "Anônimo", category: "Foco" },
  { id: "msg-83", text: "A qualidade de vida de uma pessoa é diretamente proporcional ao seu compromisso com a excelência.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-84", text: "Concentre-se no que está buscando e não no que está deixando para trás.", author: "Anônimo", category: "Foco" },
  { id: "msg-85", text: "O maior inimigo de um plano é um plano perfeito.", author: "Anônimo", category: "Planejamento" },
  { id: "msg-86", text: "A vaga existe. Alguém vai ficar com ela.", author: "Anônimo", category: "Concurso" },
  { id: "msg-87", text: "Você não precisa ser o melhor. Precisa ser aprovado.", author: "Anônimo", category: "Concurso" },
  { id: "msg-88", text: "Cada questão que você erra hoje é uma que você acerta na prova.", author: "Anônimo", category: "Concurso" },
  { id: "msg-89", text: "Constância vence intensidade.", author: "Anônimo", category: "Constância" },
  { id: "msg-90", text: "O edital não pergunta quanto você sofreu. Pergunta o que você sabe.", author: "Anônimo", category: "Concurso" },
  { id: "msg-91", text: "Estudar dois anos parece muito até você lembrar que os dois anos passam de qualquer jeito.", author: "Anônimo", category: "Concurso" },
  { id: "msg-92", text: "Reprovação é informação, não veredito.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-93", text: "Quem desiste em janeiro nunca sabe como teria sido em dezembro.", author: "Anônimo", category: "Constância" },
  { id: "msg-94", text: "Visualize sua aprovação todos os dias.", author: "Anônimo", category: "Concurso" },
  { id: "msg-95", text: "Foque no edital, ele é seu mapa.", author: "Anônimo", category: "Planejamento" },
  { id: "msg-96", text: "Planejamento bem feito reduz a ansiedade.", author: "Anônimo", category: "Planejamento" },
  { id: "msg-97", text: "Estude com objetivo, não apenas por estudar.", author: "Anônimo", category: "Foco" },
  { id: "msg-98", text: "Priorize os tópicos que mais caem em prova.", author: "Anônimo", category: "Planejamento" },
  { id: "msg-99", text: "Simulados revelam onde você precisa melhorar.", author: "Anônimo", category: "Concurso" },
  { id: "msg-100", text: "Paciência hoje, vitória amanhã.", author: "Anônimo", category: "Constância" },
  { id: "msg-101", text: "A preparação sistemática supera o improviso.", author: "Anônimo", category: "Planejamento" },
  { id: "msg-102", text: "Confie no processo e não apenas no resultado.", author: "Anônimo", category: "Constância" },
  { id: "msg-103", text: "Aprove o esforço antes de aprovar o resultado.", author: "Anônimo", category: "Constância" },
  { id: "msg-104", text: "Erros são sinais de aprendizagem, não de fracasso.", author: "Anônimo", category: "Constância" },
  { id: "msg-105", text: "Mantenha um ritmo sustentável até a prova.", author: "Anônimo", category: "Constância" },
  { id: "msg-106", text: "A prova mede o que você sabe hoje, não quem você é.", author: "Anônimo", category: "Concurso" },
  { id: "msg-107", text: "Faça primeiro as que você sabe.", author: "Anônimo", category: "Concurso" },
  { id: "msg-108", text: "Nervosismo é energia, não aviso de fracasso.", author: "Anônimo", category: "Concurso" },
  { id: "msg-109", text: "Você estudou. Confie nisso agora.", author: "Anônimo", category: "Concurso" },
  { id: "msg-110", text: "Ninguém acerta tudo. Não precisa.", author: "Anônimo", category: "Concurso" },
  { id: "msg-111", text: "Respire. Leia de novo. Responda.", author: "Anônimo", category: "Concurso" },
  { id: "msg-112", text: "Não passou. Isso dói e é justo doer.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-113", text: "Descanse antes de decidir qualquer coisa.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-114", text: "Você não perdeu o que aprendeu.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-115", text: "Erros são sinais de aprendizagem, não de fracasso.", author: "Anônimo", category: "Constância" },
  { id: "msg-116", text: "O fracasso é a oportunidade de começar de novo com mais inteligência.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-117", text: "Não tenha medo de começar de novo. Desta vez você não está começando do zero, está começando com experiência.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-118", text: "Lute como quem nunca perdeu, mas aprenda como quem já caiu.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-119", text: "A vida não é um conto de fadas, mas você pode escrever a sua história.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-120", text: "Ter sucesso é falhar repetidamente, mas sem perder o entusiasmo.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-121", text: "Você pode ser desencorajado com os erros ou aprender com eles, então siga em frente e continue falhando. Erre o máximo que puder. É aí que você vai conseguir o sucesso.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-122", text: "Se você traçar metas absurdamente altas e falhar, seu fracasso será muito melhor que o sucesso de todos.", author: "Anônimo", category: "Motivação" },
  { id: "msg-123", text: "Você não é o que os outros dizem que você é. Você é o que prova para si mesmo dia após dia.", author: "Anônimo", category: "Motivação" },
  { id: "msg-124", text: "Você é sempre mais do que pensa ser.", author: "Anônimo", category: "Motivação" },
  { id: "msg-125", text: "A confiança vem do fazer. Quanto mais você age, mais se convence de que pode.", author: "Anônimo", category: "Motivação" },
  { id: "msg-126", text: "O que define sua capacidade de aprender não é o quanto você sabe, mas o quanto você acredita que pode crescer.", author: "Anônimo", category: "Motivação" },
  { id: "msg-127", text: "O talento pode te abrir uma porta. Mas é a crença em si que te mantém lá dentro.", author: "Anônimo", category: "Motivação" },
  { id: "msg-128", text: "Você é capaz de mais do que imagina.", author: "Anônimo", category: "Motivação" },
  { id: "msg-129", text: "A mente é seu próprio lugar, e em si pode fazer um céu do inferno, um inferno do céu.", author: "Anônimo", category: "Foco" },
  { id: "msg-130", text: "A única pessoa livre é aquela que não tem medo do ridículo.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-131", text: "A criação de mil florestas está em uma semente.", author: "Anônimo", category: "Constância" },
  { id: "msg-132", text: "Seja a pessoa que você gostaria de ter ao seu lado.", author: "Anônimo", category: "Motivação" },
  { id: "msg-133", text: "Seu valor não diminui por alguém não reconhecer.", author: "Anônimo", category: "Motivação" },
  { id: "msg-134", text: "Pare de se diminuir para caber em lugares que não te merecem.", author: "Anônimo", category: "Motivação" },
  { id: "msg-135", text: "Não se compare com a versão editada da vida dos outros.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-136", text: "Ninguém acorda forte.", author: "Anônimo", category: "Constância" },
  { id: "msg-137", text: "Você já sobreviveu a dias piores. Isso aqui não vai te derrubar.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-138", text: "Não precisa acreditar 100% em você, só o suficiente pra não desistir.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-139", text: "A vida é punk, mas você é mais.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-140", text: "Aprender é a única coisa de que a mente nunca se cansa, nunca tem medo e nunca se arrepende.", author: "Anônimo", category: "Constância" },
  { id: "msg-141", text: "Eu odiava cada minuto do treinamento, mas eu disse: 'Não pare. Sofra agora para viver o resto de sua vida como um campeão.'", author: "Muhammad Ali", category: "Disciplina" },
  { id: "msg-142", text: "A melhor maneira de prever o futuro é criá-lo.", author: "Dr. Forrest C. Shaklee", category: "Motivação" },
  { id: "msg-143", text: "Não é sobre o tempo, é sobre as escolhas. Como você está gastando suas escolhas?", author: "Beverly Adamo", category: "Foco" },
  { id: "msg-144", text: "Os sonhadores são os salvadores do mundo.", author: "James Allen", category: "Motivação" },
  { id: "msg-145", text: "Tente não se tornar um homem de sucesso, mas sim tente tornar-se um homem de valor.", author: "Albert Einstein", category: "Motivação" },
  { id: "msg-146", text: "Dá-se glória apenas para aqueles que sempre sonharam com ela.", author: "Charles De Gaulle", category: "Motivação" },
  { id: "msg-147", text: "A lógica pode levar de um ponto A a um ponto B. A imaginação pode levar a qualquer lugar.", author: "Albert Einstein", category: "Motivação" },
  { id: "msg-148", text: "O sucesso normalmente vem para quem está ocupado demais para procurar por ele.", author: "Henry David Thoreau", category: "Constância" },
  { id: "msg-149", text: "Para conquistar o sucesso, você precisa aceitar todos os desafios que vierem na sua frente. Você não pode apenas aceitar os que você preferir.", author: "Mike Gafka", category: "Foco" },
  { id: "msg-150", text: "Tenha em mente que o seu desejo em atingir o sucesso é mais importante que qualquer coisa.", author: "Abraham Lincoln", category: "Foco" },
  { id: "msg-151", text: "O guerreiro de sucesso é um homem médio, mas com um foco apurado como um raio laser.", author: "Bruce Lee", category: "Foco" },
  { id: "msg-152", text: "Nosso maior medo não deve ser o fracasso, mas ser bem-sucedidos em algo que não importa.", author: "Francis Chan", category: "Foco" },
  { id: "msg-153", text: "Muitas coisas não ousamos empreender por parecerem difíceis; entretanto, são difíceis porque não ousamos empreendê-las.", author: "Sêneca", category: "Resiliência" },
  { id: "msg-154", text: "O mais forte da espécie não é o mais forte ou mais inteligente, e sim, o mais receptivo a mudança.", author: "Charles Darwin", category: "Resiliência" },
  { id: "msg-155", text: "Se você acha que a instrução é cara, experimente a ignorância.", author: "Derek Bok", category: "Concurso" },
  { id: "msg-156", text: "Educação não transforma o mundo. Educação muda pessoas. Pessoas transformam o mundo.", author: "Paulo Freire", category: "Concurso" },
  { id: "msg-157", text: "O sucesso nasce do querer, da determinação e persistência em se chegar a um objetivo.", author: "José de Alencar", category: "Constância" },
  { id: "msg-158", text: "O que nos parece uma provação amarga pode ser uma bênção disfarçada.", author: "Oscar Wilde", category: "Resiliência" },
  { id: "msg-159", text: "O tempo ensina o que a educação não alcança.", author: "Anônimo", category: "Constância" },
  { id: "msg-160", text: "A maior dádiva para o estudante é o saber adquirido, nenhum outro dom faria valer a pena tanto esforço e dedicação.", author: "Anônimo", category: "Concurso" },
  { id: "msg-161", text: "Uma frase por dia, um passo de cada vez.", author: "Anônimo", category: "Constância" },
  { id: "msg-162", text: "Cada página lida é um passo mais perto dos seus sonhos.", author: "Anônimo", category: "Constância" },
  { id: "msg-163", text: "O esforço que você coloca nos estudos é o investimento mais valioso que pode fazer.", author: "Anônimo", category: "Concurso" },
  { id: "msg-164", text: "Não se preocupe com a velocidade, preocupe-se em não parar.", author: "Anônimo", category: "Constância" },
  { id: "msg-165", text: "Desafios são oportunidades disfarçadas.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-166", text: "O conhecimento é a chave que abre portas para um futuro promissor.", author: "Anônimo", category: "Concurso" },
  { id: "msg-167", text: "Conhecimento é poder. A informação é libertadora.", author: "Anônimo", category: "Concurso" },
  { id: "msg-168", text: "Viva como se você fosse morrer amanhã. Aprenda como se você fosse viver para sempre.", author: "Anônimo", category: "Constância" },
  { id: "msg-169", text: "Estudar é polir a pedra preciosa; cultivando o espírito, purificamo-lo.", author: "Anônimo", category: "Concurso" },
  { id: "msg-170", text: "A melhor vingança é um sucesso estrondoso.", author: "Anônimo", category: "Motivação" },
  { id: "msg-171", text: "Gostaria de viver para estudar e não de estudar para viver.", author: "Anônimo", category: "Concurso" },
  { id: "msg-172", text: "O homem para ser completo tem que estudar, trabalhar e lutar.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-173", text: "Não há atalhos para nenhum lugar que valha a pena ir.", author: "Anônimo", category: "Constância" },
  { id: "msg-174", text: "Você não precisa ser ótimo para começar, mas precisa começar para ser ótimo.", author: "Anônimo", category: "Motivação" },
  { id: "msg-175", text: "Não deixe que o que você não pode fazer interfira no que você pode fazer.", author: "Anônimo", category: "Foco" },
  { id: "msg-176", text: "Uma pessoa que nunca cometeu um erro nunca tentou nada novo.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-177", text: "A mente não é um recipiente a ser preenchido, mas um fogo a ser aceso.", author: "Anônimo", category: "Foco" },
  { id: "msg-178", text: "O não você já tem, agora corra atrás do sim.", author: "Anônimo", category: "Motivação" },
  { id: "msg-179", text: "A vida começa onde sua zona de conforto termina.", author: "Anônimo", category: "Motivação" },
  { id: "msg-180", text: "O primeiro passo é o mais difícil, mas é o que importa.", author: "Anônimo", category: "Motivação" },
  { id: "msg-181", text: "A vitória é a soma de pequenos esforços repetidos dia após dia.", author: "Anônimo", category: "Constância" },
  { id: "msg-182", text: "Quem não arrisca, não petisca, mas também não aprende.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-183", text: "Água parada cria mosquito. Vida parada cria ansiedade.", author: "Anônimo", category: "Constância" },
  { id: "msg-184", text: "O silêncio também responde e, às vezes, é a resposta mais forte.", author: "Anônimo", category: "Foco" },
  { id: "msg-185", text: "Você não pode mudar o vento, mas pode ajustar as velas.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-186", text: "Não implore por atenção. Gente de verdade fica sem precisar pedir.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-187", text: "A sua paz vale mais do que qualquer explicação.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-188", text: "Seja tão bom que não te perdoarem pela sua ausência.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-189", text: "Respeito não se exige, se conquista.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-190", text: "Cuidado com a boca que te elogia e com as mãos que não te ajudam.", author: "Anônimo", category: "Foco" },
  { id: "msg-191", text: "Valorize quem fica, mesmo quando você não tem nada a oferecer.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-192", text: "Gente que soma nunca te diminui.", author: "Anônimo", category: "Foco" },
  { id: "msg-193", text: "Quem te quer perto não te coloca contra a parede.", author: "Anônimo", category: "Foco" },
  { id: "msg-194", text: "Não confunda sua paz com solidão.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-195", text: "Se não está bom para os dois, não está bom para ninguém.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-196", text: "Aprenda a ficar calado enquanto as coisas se ajeitam.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-197", text: "Fogo de palha queima rápido e não esquenta ninguém.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-198", text: "Não deixe para ser feliz quando tudo estiver perfeito.", author: "Anônimo", category: "Motivação" },
  { id: "msg-199", text: "Não adianta correr se você está no caminho errado.", author: "Anônimo", category: "Foco" },
  { id: "msg-200", text: "O que é seu virá sem puxar, sem implorar.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-201", text: "Tem gente que só te procura quando o ralo entope.", author: "Anônimo", category: "Foco" },
  { id: "msg-202", text: "Não troque o certo pelo duvidoso.", author: "Anônimo", category: "Foco" },
  { id: "msg-203", text: "O sol nasce para todos, mas quem acorda cedo vê.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-204", text: "O orgulho afasta, a humildade aproxima.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-205", text: "Antes só do que mal acompanhado de si mesmo.", author: "Anônimo", category: "Foco" },
  { id: "msg-206", text: "Liberdade é não dever satisfação para quem não te acrescenta.", author: "Anônimo", category: "Foco" },
  { id: "msg-207", text: "A sua energia é seu bem mais precioso. Não gaste com qualquer um.", author: "Anônimo", category: "Foco" },
  { id: "msg-208", text: "Gente que não te valoriza, não merece seu tempo.", author: "Anônimo", category: "Foco" },
  { id: "msg-209", text: "Não pare até que você esteja lá.", author: "Anônimo", category: "Constância" },
  { id: "msg-210", text: "Comece uma hora antes. Pode mudar muito.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-211", text: "O cansaço suga menos do que o arrependimento.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-212", text: "Foque no controle do seu esforço, não do resultado.", author: "Anônimo", category: "Foco" },
  { id: "msg-213", text: "Aprender é um investimento que ninguém pode tirar de você.", author: "Anônimo", category: "Concurso" },
  { id: "msg-214", text: "Estude, pois o conhecimento é a única coisa que não podem nos tirar.", author: "Anônimo", category: "Concurso" },
  { id: "msg-215", text: "Tempo de estudos nunca é tempo perdido. Você sempre ganha mais conhecimento.", author: "Anônimo", category: "Concurso" },
  { id: "msg-216", text: "Quanto mais estudos, mais conhecimento. Quanto mais conhecimento, mais sabedoria para mudar o mundo.", author: "Anônimo", category: "Concurso" },
  { id: "msg-217", text: "Um ladrão rouba um tesouro, mas não furta a inteligência. Uma crise destrói uma herança, mas não uma profissão. Não importa se você não tem dinheiro, você é uma pessoa rica, pois possui o maior de todos os capitais: a sua inteligência. Invista nela. Estude!", author: "Anônimo", category: "Concurso" },
  { id: "msg-218", text: "O conhecimento é a chave que abre portas.", author: "Anônimo", category: "Concurso" },
  { id: "msg-219", text: "A educação é a premissa do progresso em cada sociedade, em cada família.", author: "Anônimo", category: "Concurso" },
  { id: "msg-220", text: "O aprendizado é uma viagem sem fim.", author: "Anônimo", category: "Constância" },
  { id: "msg-221", text: "Se você não estudar para alcançar o futuro que quer, deve aceitar o futuro que vier.", author: "Anônimo", category: "Concurso" },
  { id: "msg-222", text: "Aquele que não luta pelo futuro que quer, deve aceitar o futuro que vier.", author: "Anônimo", category: "Concurso" },
  { id: "msg-223", text: "Não aprenda só o superficial, pois o difícil pode se tornar barreira vencida.", author: "Anônimo", category: "Concurso" },
  { id: "msg-224", text: "Para aquele cujo momento chegou agora, nunca é tarde demais!", author: "Anônimo", category: "Motivação" },
  { id: "msg-225", text: "Aprender o ABC não basta, mas aprenda-o.", author: "Anônimo", category: "Concurso" },
  { id: "msg-226", text: "Se não tens teto, cobre-te de saber.", author: "Anônimo", category: "Concurso" },
  { id: "msg-227", text: "Estudar não embeleza, mas faz de você alguém mais interessante.", author: "Anônimo", category: "Concurso" },
  { id: "msg-228", text: "Aprender é a única coisa de que a mente nunca se cansa.", author: "Anônimo", category: "Constância" },
  { id: "msg-229", text: "O futuro recompensa os que continuam. Eu não era o mais esperto — apenas o que nunca desistia.", author: "Anônimo", category: "Constância" },
  { id: "msg-230", text: "Estudar é como plantar: você não colhe no mesmo dia, mas o futuro agradece a cada semente.", author: "Anônimo", category: "Constância" },
  { id: "msg-231", text: "Comece a estudar hoje para vencer amanhã.", author: "Anônimo", category: "Concurso" },
  { id: "msg-232", text: "Estudar é a única forma de um dia vir a ter sucesso.", author: "Anônimo", category: "Concurso" },
  { id: "msg-233", text: "Se você empregasse seu tempo em estudar, pensar e planejar todos os dias poderia desenvolver e usar o poder que talvez mudasse todo o curso do seu destino.", author: "Anônimo", category: "Planejamento" },
  { id: "msg-234", text: "Não deixe seu futuro nas mãos da sorte.", author: "Anônimo", category: "Concurso" },
  { id: "msg-235", text: "Pratique, estude e aprenda.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-236", text: "Acredito cada vez mais que não se deve julgar o bom Deus por este mundo, pois foi um estudo dele que saiu errado.", author: "Anônimo", category: "Motivação" },
  { id: "msg-237", text: "Escolha uma ideia. Faça dessa ideia a sua vida. Pense nela, sonhe com ela, viva pensando nela. Deixe cérebro, músculos, nervos, todas as partes do seu corpo serem preenchidas com essa ideia. Esse é o caminho para o sucesso.", author: "Anônimo", category: "Foco" },
  { id: "msg-238", text: "Os empreendedores falham, em média, 3,8 vezes antes do sucesso final. O que separa os bem-sucedidos dos outros é a persistência.", author: "Anônimo", category: "Constância" },
  { id: "msg-239", text: "Essa é exatamente a pergunta que todos deveriam estar se perguntando, por que não? – Por que não você? Por que não agora…?", author: "Timothy Ferriss", category: "Motivação" },
  { id: "msg-240", text: "Vamos inventar o amanhã e parar de nos preocupar com o passado.", author: "Steve Jobs", category: "Motivação" },
  { id: "msg-241", text: "Dois homens olham pela janela. Um vê a lama e o outro vê as estrelas.", author: "Frederich Langbridge", category: "Foco" },
  { id: "msg-242", text: "Os milagres acontecem, às vezes. Mas é preciso trabalhar tremendamente para que aconteçam.", author: "Peter Drucker", category: "Disciplina" },
  { id: "msg-243", text: "Não há nada tão inútil quanto fazer eficientemente o que não deveria ser feito.", author: "Peter Drucker", category: "Foco" },
  { id: "msg-244", text: "A questão essencial não é 'o quanto ocupado você está', mas sim 'com o que você está ocupado'.", author: "Oprah Winfrey", category: "Foco" },
  { id: "msg-245", text: "As pessoas costumam dizer que a motivação não dura para sempre. Bem, nem o efeito do banho, por isso recomenda-se diariamente.", author: "Zig Ziglar", category: "Motivação" },
  { id: "msg-246", text: "Toda ação humana, quer se torne positiva ou negativa, precisa depender de motivação.", author: "Dalai Lama", category: "Motivação" },
  { id: "msg-247", text: "Resultados são obtidos aproveitando oportunidades e não resolvendo problemas.", author: "Peter Drucker", category: "Foco" },
  { id: "msg-248", text: "Acredite no processo.", author: "Anônimo", category: "Constância" },
  { id: "msg-249", text: "Seja gentil consigo mesmo nos dias ruins.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-250", text: "Permita-se descansar sem desistir.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-251", text: "Afaste comparações, cada jornada é única.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-252", text: "Peça apoio quando precisar, não precisa ser só.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-253", text: "Recompense-se por cada meta alcançada.", author: "Anônimo", category: "Motivação" },
  { id: "msg-254", text: "Durma bem para seu cérebro absorver o conteúdo.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-255", text: "Confie nisso agora.", author: "Anônimo", category: "Motivação" },
  { id: "msg-256", text: "Não mude por ninguém, mude por você mesmo. Essa é a essência da mudança. Mudar porque queremos progredir e não porque queremos impressionar.", author: "Anônimo", category: "Motivação" },
  { id: "msg-257", text: "Tenha até pesadelos, se necessário for. Mas sonhe.", author: "Anônimo", category: "Motivação" },
  { id: "msg-258", text: "Você não constrói nada sozinho. Você descobre o que as pessoas querem e então constrói para elas.", author: "Anônimo", category: "Foco" },
  { id: "msg-259", text: "Democracia é oportunizar a todos o mesmo ponto de partida. Quanto ao ponto de chegada, depende de cada um.", author: "Anônimo", category: "Motivação" },
  { id: "msg-260", text: "Um homem com coragem faz uma maioria.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-261", text: "Frequentemente, o melhor marketing não parece realmente marketing.", author: "Seth Godin", category: "Foco" },
  { id: "msg-262", text: "Se você for realmente relevante para seu público, ele prestará atenção em você.", author: "Martha Gabriel", category: "Foco" },
  { id: "msg-263", text: "Meu trabalho não é o de pegar leve com as pessoas, meu trabalho é o de tornar elas melhores.", author: "Steve Jobs", category: "Disciplina" },
  { id: "msg-264", text: "O custo de estar errado é menor do que o custo de não fazer nada.", author: "Seth Godin", category: "Motivação" },
  { id: "msg-265", text: "Quanto mais difícil fica, mais próximo está o sucesso.", author: "Chris Garrett", category: "Resiliência" },
  { id: "msg-266", text: "Crie algo que as pessoas queiram compartilhar.", author: "John Jantsch", category: "Foco" },
  { id: "msg-267", text: "Se você quer entender como um leão ruge, não vá ao zoológico. Vá à selva.", author: "Jim Stengel", category: "Foco" },
  { id: "msg-268", text: "Empreendedores são aqueles que entendem que há uma pequena diferença entre obstáculos e oportunidades e são capazes de transformar ambos em vantagem.", author: "Nicolau Maquiavel", category: "Resiliência" },
  { id: "msg-269", text: "Existe o risco que você não pode jamais correr e existe o risco que você não pode deixar de correr.", author: "Peter Drucker", category: "Foco" },
  { id: "msg-270", text: "O segredo do empreendedorismo é ter 100% de convicção com apenas 80% da resposta.", author: "Aaron Levie", category: "Foco" },
  { id: "msg-271", text: "Digo a todo jovem que quer ser empreendedor que é preciso se superar.", author: "Eike Batista", category: "Motivação" },
  { id: "msg-272", text: "As dificuldades e obstáculos são matéria-prima para o verdadeiro empreendedor.", author: "Carlos Hilsdorf", category: "Resiliência" },
  { id: "msg-273", text: "Nos negócios, as oportunidades são como ônibus, há sempre um outro vindo.", author: "Richard Branson", category: "Motivação" },
  { id: "msg-274", text: "Um líder não é alguém a quem foi dada uma coroa, mas quem foi dada a responsabilidade fazer sobressair o melhor que há nos outros.", author: "Jack Welch", category: "Disciplina" },
  { id: "msg-275", text: "Uma palavra grosseira, uma expressão bizarra, ensinou-me por vezes mais do que dez belas frases.", author: "Denis Diderot", category: "Foco" },
  { id: "msg-276", text: "Existe apenas um chefe, o cliente. E ele pode demitir todos na empresa, desde o presidente, simplesmente gastando o dinheiro em outro lugar.", author: "Sam Walton", category: "Foco" },
  { id: "msg-277", text: "Marketing é importante demais para ser deixado para o departamento de marketing.", author: "David Packard", category: "Foco" },
  { id: "msg-278", text: "Lucro é subproduto das coisas bem feitas.", author: "Philip Kotler", category: "Disciplina" },
  { id: "msg-279", text: "A sua cabeça é fértil? Você só fala abobrinha? Plante as abobrinhas e saia vendendo.", author: "Lucas Barbosa", category: "Motivação" },
  { id: "msg-280", text: "Querer fazer tudo para todos é o primeiro passo para não fazer nada a ninguém.", author: "Anônimo", category: "Foco" },
  { id: "msg-281", text: "Grandes empreendedores estão confortáveis em estarem desconfortáveis.", author: "Steve Blank", category: "Resiliência" },
  { id: "msg-282", text: "Quer conquistar algo? Conquiste calos nas mãos e esfole os joelhos.", author: "Cris Westphal", category: "Disciplina" },
  { id: "msg-283", text: "Fique contente em agir. Deixe a fala para os outros.", author: "Baltasar Gracián", category: "Disciplina" },
  { id: "msg-284", text: "O que pode ser medido pode ser melhorado.", author: "Peter Drucker", category: "Planejamento" },
  { id: "msg-285", text: "Quanto maior o artista, maior a dúvida. Confiança grande demais é algo destinado aos menos talentosos como um prêmio de consolação.", author: "Robert Hughes", category: "Foco" },
  { id: "msg-286", text: "Eu devo meu sucesso a meu hábito de respeitosamente ouvir conselhos e fazer exatamente o contrário.", author: "G. K. Chesterton", category: "Foco" },
  { id: "msg-287", text: "Você deve lutar mais de uma batalha para se tornar um vencedor.", author: "Margaret Thatcher", category: "Resiliência" },
  { id: "msg-288", text: "Se você não traçou um plano para você mesmo, é possível que você caia no plano de outra pessoa. E adivinha o que ele planejou para você? Não muito.", author: "Jim Rohn", category: "Planejamento" },
  { id: "msg-289", text: "A motivação é o que faz o empreendedor começar. O hábito é o que o mantém.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-290", text: "As companhias prestam muita atenção ao custo de fazer alguma coisa. Deviam preocupar-se mais com os custos de não fazer nada.", author: "Philip Kotler", category: "Foco" },
  { id: "msg-291", text: "Cada dia é uma nova oportunidade.", author: "Anônimo", category: "Motivação" },
  { id: "msg-292", text: "O esforço de hoje é o resultado de amanhã.", author: "Anônimo", category: "Constância" },
  { id: "msg-293", text: "A vitória é a soma de pequenos esforços repetidos dia após dia.", author: "Anônimo", category: "Constância" },
  { id: "msg-294", text: "O primeiro passo é o mais difícil, mas é o que importa.", author: "Anônimo", category: "Motivação" },
  { id: "msg-295", text: "A vida começa onde sua zona de conforto termina.", author: "Anônimo", category: "Motivação" },
  { id: "msg-296", text: "O não você já tem, agora corra atrás do sim.", author: "Anônimo", category: "Motivação" },
  { id: "msg-297", text: "A sua paz vale mais do que qualquer explicação.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-298", text: "Crescer dói. Mas ficar no mesmo lugar dói para sempre.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-299", text: "O preço da disciplina será sempre menor que o do arrependimento.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-300", text: "Quem quer fazer um jeito arruma. Quem não quer, arruma desculpa.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-301", text: "Não confunda sua paz com solidão.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-302", text: "Não espere a motivação chegar. Comece sem ela e ela virá.", author: "Anônimo", category: "Motivação" },
  { id: "msg-303", text: "Não deixe para ser feliz quando tudo estiver perfeito.", author: "Anônimo", category: "Motivação" },
  { id: "msg-304", text: "O que os outros pensam de você é problema deles.", author: "Anônimo", category: "Foco" },
  { id: "msg-305", text: "Não adianta correr se você está no caminho errado.", author: "Anônimo", category: "Foco" },
  { id: "msg-306", text: "O que é seu virá sem puxar, sem implorar.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-307", text: "Não troque o certo pelo duvidoso.", author: "Anônimo", category: "Foco" },
  { id: "msg-308", text: "O sol nasce para todos, mas quem acorda cedo vê.", author: "Anônimo", category: "Disciplina" },
  { id: "msg-309", text: "O orgulho afasta, a humildade aproxima.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-310", text: "Não se cobre tanto por algo que você ainda está aprendendo.", author: "Anônimo", category: "Constância" },
  { id: "msg-311", text: "Não deixe que o ontem atrapalhe o amanhã.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-312", text: "Seja a pessoa que você gostaria de ter ao seu lado.", author: "Anônimo", category: "Motivação" },
  { id: "msg-313", text: "Liberdade é não dever satisfação para quem não te acrescenta.", author: "Anônimo", category: "Foco" },
  { id: "msg-314", text: "Não se compare com a versão editada da vida dos outros.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-315", text: "Água parada cria mosquito. Vida parada cria ansiedade.", author: "Anônimo", category: "Constância" },
  { id: "msg-316", text: "Não tenha medo de começar de novo.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-317", text: "A sua energia é seu bem mais precioso.", author: "Anônimo", category: "Foco" },
  { id: "msg-318", text: "Erga a cabeça, sacode a poeira e dá a volta por cima.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-319", text: "Pare de se diminuir para caber em lugares que não te merecem.", author: "Anônimo", category: "Motivação" },
  { id: "msg-320", text: "Você estudou. Confie nisso agora.", author: "Anônimo", category: "Concurso" },
  { id: "msg-321", text: "Nervosismo é energia, não aviso de fracasso.", author: "Anônimo", category: "Concurso" },
  { id: "msg-322", text: "Faça primeiro as que você sabe.", author: "Anônimo", category: "Concurso" },
  { id: "msg-323", text: "Ninguém acerta tudo. Não precisa.", author: "Anônimo", category: "Concurso" },
  { id: "msg-324", text: "Respire. Leia de novo. Responda.", author: "Anônimo", category: "Concurso" },
  { id: "msg-325", text: "A prova mede o que você sabe hoje, não quem você é.", author: "Anônimo", category: "Concurso" },
  { id: "msg-326", text: "A vaga existe. Alguém vai ficar com ela.", author: "Anônimo", category: "Concurso" },
  { id: "msg-327", text: "Cada questão que você erra hoje é uma que você acerta na prova.", author: "Anônimo", category: "Concurso" },
  { id: "msg-328", text: "Constância vence intensidade.", author: "Anônimo", category: "Constância" },
  { id: "msg-329", text: "O edital não pergunta quanto você sofreu. Pergunta o que você sabe.", author: "Anônimo", category: "Concurso" },
  { id: "msg-330", text: "Reprovação é informação, não veredito.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-331", text: "Quem desiste em janeiro nunca sabe como teria sido em dezembro.", author: "Anônimo", category: "Constância" },
  { id: "msg-332", text: "Foque no edital, ele é seu mapa.", author: "Anônimo", category: "Planejamento" },
  { id: "msg-333", text: "Planejamento bem feito reduz a ansiedade.", author: "Anônimo", category: "Planejamento" },
  { id: "msg-334", text: "Estude com objetivo, não apenas por estudar.", author: "Anônimo", category: "Foco" },
  { id: "msg-335", text: "Simulados revelam onde você precisa melhorar.", author: "Anônimo", category: "Concurso" },
  { id: "msg-336", text: "Paciência hoje, vitória amanhã.", author: "Anônimo", category: "Constância" },
  { id: "msg-337", text: "A preparação sistemática supera o improviso.", author: "Anônimo", category: "Planejamento" },
  { id: "msg-338", text: "Confie no processo e não apenas no resultado.", author: "Anônimo", category: "Constância" },
  { id: "msg-339", text: "Aprove o esforço antes de aprovar o resultado.", author: "Anônimo", category: "Constância" },
  { id: "msg-340", text: "Erros são sinais de aprendizagem, não de fracasso.", author: "Anônimo", category: "Constância" },
  { id: "msg-341", text: "Mantenha um ritmo sustentável até a prova.", author: "Anônimo", category: "Constância" },
  { id: "msg-342", text: "Visualize sua aprovação todos os dias.", author: "Anônimo", category: "Concurso" },
  { id: "msg-343", text: "Estude dois anos que eles passam de qualquer jeito.", author: "Anônimo", category: "Concurso" },
  { id: "msg-344", text: "Recomeçar não é fracasso, é coragem.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-345", text: "Quando desanimar, lembre-se do porquê.", author: "Anônimo", category: "Motivação" },
  { id: "msg-346", text: "Afaste comparações, cada jornada é única.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-347", text: "Permita-se descansar sem desistir.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-348", text: "Transforme frustração em combustível.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-349", text: "Peça apoio quando precisar, não precisa ser só.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-350", text: "Foque no controle do seu esforço, não do resultado.", author: "Anônimo", category: "Foco" },
  { id: "msg-351", text: "Cada dia ruim é temporário, continue.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-352", text: "Você não perdeu o que aprendeu.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-353", text: "Descanse antes de decidir qualquer coisa.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-354", text: "Não passou. Isso dói e é justo doer.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-355", text: "O fracasso é a oportunidade de começar de novo com mais inteligência.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-356", text: "Lute como quem nunca perdeu, mas aprenda como quem já caiu.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-357", text: "A vida não é um conto de fadas, mas você pode escrever a sua história.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-358", text: "Desta vez você não está começando do zero, está começando com experiência.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-359", text: "Não tenha medo de começar de novo.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-360", text: "Ter sucesso é falhar repetidamente, mas sem perder o entusiasmo.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-361", text: "Você pode ser desencorajado com os erros ou aprender com eles.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-362", text: "Erre o máximo que puder. É aí que você vai conseguir o sucesso.", author: "Anônimo", category: "Resiliência" },
  { id: "msg-363", text: "Acredite que você pode, assim você já está no meio do caminho.", author: "Anônimo", category: "Motivação" },
  { id: "msg-364", text: "Nunca pare. Sofra agora para viver o resto de sua vida como um campeão.", author: "Muhammad Ali", category: "Disciplina" },
  { id: "msg-365", text: "Acredite no processo.", author: "Anônimo", category: "Constância" },
]

/**
 * Retorna a mensagem do dia de forma 100% determinística e estável para cada data.
 * O F5 na mesma data nunca altera a frase.
 */
export function getDailyMessage(date = new Date()): DailyMessage {
  const year = date.getFullYear()
  const month = date.getMonth()
  const day = date.getDate()
  const daySeed = year * 10000 + (month + 1) * 100 + day
  const index = Math.abs(daySeed) % DAILY_MESSAGES.length
  const found = DAILY_MESSAGES[index]
  if (found) return found

  return {
    id: "msg-default",
    text: "Estude enquanto eles dormem, trabalhe enquanto eles descansam, viva o que eles sonham.",
    author: "Provérbio",
    category: "Motivação",
  }
}
