/**
 * Domínio de Conquistas — NomeIA
 * "Sua preparação rumo à nomeação."
 */

export type AchievementRarity = "comum" | "rara" | "epica" | "lendaria"

export interface AchievementDefinition {
  id: string
  categoryId: string
  title: string
  description: string
  iconName: string
  rarity: AchievementRarity
  targetValue: number
  unit:
    | "questoes"
    | "horas"
    | "dias"
    | "revisoes"
    | "simulados"
    | "topicos"
    | "porcentagem"
    | "semanas"
    | "sessoes"
    | "acao"
}

export interface AchievementCategoryDef {
  id: string
  title: string
  subtitle: string
  color: string
  iconName: string
}

export const ACHIEVEMENT_CATEGORIES: AchievementCategoryDef[] = [
  {
    id: "primeira-conquista",
    title: "Primeira Conquista",
    subtitle: "Marcos fundamentais que inauguram sua preparação estratégica no NomeIA.",
    color: "#2563EB",
    iconName: "Sparkles",
  },
  {
    id: "constancia",
    title: "Constância",
    subtitle: "Sequências de dias reais de estudo para construir disciplina inabalável.",
    color: "#16A34A",
    iconName: "Flame",
  },
  {
    id: "volume",
    title: "Volume de Estudo",
    subtitle: "Acúmulo real de horas líquidas de dedicação aos seus objetivos.",
    color: "#6366F1",
    iconName: "Clock",
  },
  {
    id: "questoes",
    title: "Questões",
    subtitle: "Volume e rodagem de treino prático com resolução ativa de questões.",
    color: "#F97316",
    iconName: "ListChecks",
  },
  {
    id: "desempenho",
    title: "Desempenho em Questões",
    subtitle: "Acurácia e precisão em baterias válidas de questões.",
    color: "#8B5CF6",
    iconName: "TrendingUp",
  },
  {
    id: "revisoes",
    title: "Revisões",
    subtitle: "Retenção de longo prazo com ciclos inteligentes de repetição espaçada.",
    color: "#0D9488",
    iconName: "RotateCcw",
  },
  {
    id: "simulados",
    title: "Simulados",
    subtitle: "Treino em ambiente real de prova e controle de tempo.",
    color: "#EA580C",
    iconName: "ClipboardCheck",
  },
  {
    id: "planejamento",
    title: "Planejamento & Aderência",
    subtitle: "Execução consistente da rotina e cumprimento do cronograma planejado.",
    color: "#0284C7",
    iconName: "CalendarCheck",
  },
  {
    id: "cobertura",
    title: "Cobertura do Edital",
    subtitle: "Avanço estruturado através de cada disciplina e tópico cadastrado.",
    color: "#06B6D4",
    iconName: "Layers",
  },
  {
    id: "alta-performance",
    title: "Alta Performance & Horários",
    subtitle: "Excelência por disciplina, domínio de rotina e faixas horárias produtivas.",
    color: "#D97706",
    iconName: "Trophy",
  },
]

export const ACHIEVEMENTS_LIST: AchievementDefinition[] = [
  // 1. PRIMEIRA CONQUISTA
  {
    id: "FIRST_ACCOUNT",
    categoryId: "primeira-conquista",
    title: "Conta em Movimento",
    description: "Complete o cadastro inicial e ative sua conta no NomeIA.",
    iconName: "UserCheck",
    rarity: "comum",
    targetValue: 1,
    unit: "acao",
  },
  {
    id: "FIRST_ONBOARDING",
    categoryId: "primeira-conquista",
    title: "Rumo Definido",
    description: "Conclua o onboarding e defina suas preferências de estudo.",
    iconName: "Compass",
    rarity: "comum",
    targetValue: 1,
    unit: "acao",
  },
  {
    id: "FIRST_PLAN",
    categoryId: "primeira-conquista",
    title: "Primeiro Planejamento",
    description: "Crie seu primeiro planejamento semanal de estudos.",
    iconName: "CalendarDays",
    rarity: "comum",
    targetValue: 1,
    unit: "acao",
  },
  {
    id: "FIRST_SESSION",
    categoryId: "primeira-conquista",
    title: "Primeiro Registro",
    description: "Registre e conclua sua primeira sessão de estudo.",
    iconName: "Play",
    rarity: "comum",
    targetValue: 1,
    unit: "acao",
  },
  {
    id: "FIRST_QUESTION",
    categoryId: "primeira-conquista",
    title: "Primeiras Questões",
    description: "Resolva e registre suas primeiras questões de treino.",
    iconName: "CheckCircle2",
    rarity: "comum",
    targetValue: 1,
    unit: "acao",
  },
  {
    id: "FIRST_REVIEW",
    categoryId: "primeira-conquista",
    title: "Primeira Revisão",
    description: "Conclua sua primeira sessão de revisão espaçada.",
    iconName: "RotateCcw",
    rarity: "comum",
    targetValue: 1,
    unit: "acao",
  },

  // 2. CONSTÂNCIA
  {
    id: "STREAK_3_DAYS",
    categoryId: "constancia",
    title: "Ritmo Inicial",
    description: "Mantenha uma sequência de 3 dias consecutivos de estudo real.",
    iconName: "Flame",
    rarity: "comum",
    targetValue: 3,
    unit: "dias",
  },
  {
    id: "STREAK_7_DAYS",
    categoryId: "constancia",
    title: "Semana em Alta",
    description: "Estude por 7 dias consecutivos sem quebrar o ritmo.",
    iconName: "Flame",
    rarity: "comum",
    targetValue: 7,
    unit: "dias",
  },
  {
    id: "STREAK_14_DAYS",
    categoryId: "constancia",
    title: "Quinzena Consistente",
    description: "Atinja 14 dias seguidos com registros de estudo.",
    iconName: "ShieldCheck",
    rarity: "rara",
    targetValue: 14,
    unit: "dias",
  },
  {
    id: "STREAK_30_DAYS",
    categoryId: "constancia",
    title: "Mês de Disciplina",
    description: "Complete 30 dias consecutivos de preparação consistente.",
    iconName: "ShieldCheck",
    rarity: "rara",
    targetValue: 30,
    unit: "dias",
  },
  {
    id: "STREAK_90_DAYS",
    categoryId: "constancia",
    title: "Trimestre de Constância",
    description: "Mantenha 90 dias ininterruptos construindo sua aprovação.",
    iconName: "Award",
    rarity: "epica",
    targetValue: 90,
    unit: "dias",
  },
  {
    id: "STREAK_180_DAYS",
    categoryId: "constancia",
    title: "Sem Quebrar",
    description: "Alcance a impressionante marca de 180 dias consecutivos.",
    iconName: "Award",
    rarity: "epica",
    targetValue: 180,
    unit: "dias",
  },
  {
    id: "STREAK_365_DAYS",
    categoryId: "constancia",
    title: "Ano de Preparação",
    description: "1 ano inteiro de estudo diário ininterrupto rumo à nomeação.",
    iconName: "Trophy",
    rarity: "lendaria",
    targetValue: 365,
    unit: "dias",
  },

  // 3. VOLUME DE ESTUDO
  {
    id: "HOURS_10",
    categoryId: "volume",
    title: "Primeiras 10 Horas",
    description: "Acumule 10 horas líquidas de estudo registradas.",
    iconName: "Clock",
    rarity: "comum",
    targetValue: 10,
    unit: "horas",
  },
  {
    id: "HOURS_50",
    categoryId: "volume",
    title: "Base Construída",
    description: "Acumule 50 horas de dedicação aos seus estudos.",
    iconName: "Clock",
    rarity: "comum",
    targetValue: 50,
    unit: "horas",
  },
  {
    id: "HOURS_100",
    categoryId: "volume",
    title: "Ritmo de Preparação",
    description: "Alcance a marca de 100 horas líquidas de estudo.",
    iconName: "Clock",
    rarity: "rara",
    targetValue: 100,
    unit: "horas",
  },
  {
    id: "HOURS_250",
    categoryId: "volume",
    title: "Carga Consistente",
    description: "Atinja 250 horas de dedicação acumuladas.",
    iconName: "Hourglass",
    rarity: "rara",
    targetValue: 250,
    unit: "horas",
  },
  {
    id: "HOURS_500",
    categoryId: "volume",
    title: "Preparação Séria",
    description: "Acumule 500 horas líquidas de estudo estruturado.",
    iconName: "Hourglass",
    rarity: "epica",
    targetValue: 500,
    unit: "horas",
  },
  {
    id: "HOURS_750",
    categoryId: "volume",
    title: "Alta Dedicação",
    description: "Alcance 750 horas de preparação ativa.",
    iconName: "Hourglass",
    rarity: "epica",
    targetValue: 750,
    unit: "horas",
  },
  {
    id: "HOURS_1000",
    categoryId: "volume",
    title: "1.000 Horas",
    description: "Atinja o marco de 1.000 horas líquidas de estudo.",
    iconName: "Medal",
    rarity: "epica",
    targetValue: 1000,
    unit: "horas",
  },
  {
    id: "HOURS_2000",
    categoryId: "volume",
    title: "2.000 Horas",
    description: "Acumule 2.000 horas de dedicação e conteúdo estudado.",
    iconName: "Medal",
    rarity: "lendaria",
    targetValue: 2000,
    unit: "horas",
  },
  {
    id: "HOURS_3000",
    categoryId: "volume",
    title: "3.000 Horas",
    description: "Alcance a marca extraordinária de 3.000 horas líquidas.",
    iconName: "Trophy",
    rarity: "lendaria",
    targetValue: 3000,
    unit: "horas",
  },
  {
    id: "HOURS_5000",
    categoryId: "volume",
    title: "5.000 Horas",
    description: "5.000 horas de dedicação acumuladas rumo ao topo.",
    iconName: "Trophy",
    rarity: "lendaria",
    targetValue: 5000,
    unit: "horas",
  },

  // 4. QUESTÕES
  {
    id: "QUESTIONS_1",
    categoryId: "questoes",
    title: "Primeira Questão",
    description: "Resolva sua primeira questão na plataforma.",
    iconName: "CheckSquare",
    rarity: "comum",
    targetValue: 1,
    unit: "questoes",
  },
  {
    id: "QUESTIONS_50",
    categoryId: "questoes",
    title: "Aquecimento",
    description: "Resolva 50 questões de treino prático.",
    iconName: "ListChecks",
    rarity: "comum",
    targetValue: 50,
    unit: "questoes",
  },
  {
    id: "QUESTIONS_250",
    categoryId: "questoes",
    title: "Treino Ativo",
    description: "Conclua 250 questões resolvidas.",
    iconName: "ListChecks",
    rarity: "comum",
    targetValue: 250,
    unit: "questoes",
  },
  {
    id: "QUESTIONS_500",
    categoryId: "questoes",
    title: "Ritmo de Prova",
    description: "Atinja o marco de 500 questões resolvidas.",
    iconName: "ListChecks",
    rarity: "rara",
    targetValue: 500,
    unit: "questoes",
  },
  {
    id: "QUESTIONS_1000",
    categoryId: "questoes",
    title: "Bateria de Questões",
    description: "Resolva 1.000 questões durante sua preparação.",
    iconName: "Layers",
    rarity: "rara",
    targetValue: 1000,
    unit: "questoes",
  },
  {
    id: "QUESTIONS_2500",
    categoryId: "questoes",
    title: "Volume Competitivo",
    description: "Atinja 2.500 questões resolvidas.",
    iconName: "Layers",
    rarity: "epica",
    targetValue: 2500,
    unit: "questoes",
  },
  {
    id: "QUESTIONS_5000",
    categoryId: "questoes",
    title: "Alta Rodagem",
    description: "Resolva 5.000 questões na sua trajetória de estudos.",
    iconName: "Medal",
    rarity: "epica",
    targetValue: 5000,
    unit: "questoes",
  },
  {
    id: "QUESTIONS_10000",
    categoryId: "questoes",
    title: "Máquina de Questões",
    description: "Alcance o marco de 10.000 questões concluídas.",
    iconName: "Trophy",
    rarity: "lendaria",
    targetValue: 10000,
    unit: "questoes",
  },
  {
    id: "QUESTIONS_25000",
    categoryId: "questoes",
    title: "25 Mil em Treino",
    description: "25.000 questões resolvidas com consistência e método.",
    iconName: "Trophy",
    rarity: "lendaria",
    targetValue: 25000,
    unit: "questoes",
  },

  // 5. DESEMPENHO EM QUESTÕES
  {
    id: "ACCURACY_70",
    categoryId: "desempenho",
    title: "Primeiro Aproveitamento",
    description: "Atingir 70% de acertos em amostra mínima de 30 questões.",
    iconName: "TrendingUp",
    rarity: "comum",
    targetValue: 70,
    unit: "porcentagem",
  },
  {
    id: "ACCURACY_80",
    categoryId: "desempenho",
    title: "Zona de Segurança",
    description: "Atingir 80% de acertos em amostra mínima de 50 questões.",
    iconName: "TrendingUp",
    rarity: "rara",
    targetValue: 80,
    unit: "porcentagem",
  },
  {
    id: "ACCURACY_85",
    categoryId: "desempenho",
    title: "Desempenho Forte",
    description: "Atingir 85% de acertos em amostra mínima de 100 questões.",
    iconName: "Award",
    rarity: "rara",
    targetValue: 85,
    unit: "porcentagem",
  },
  {
    id: "ACCURACY_90",
    categoryId: "desempenho",
    title: "Faixa Competitiva",
    description: "Atingir 90% de acertos em amostra mínima de 250 questões.",
    iconName: "Medal",
    rarity: "epica",
    targetValue: 90,
    unit: "porcentagem",
  },
  {
    id: "ACCURACY_95",
    categoryId: "desempenho",
    title: "Alta Precisão",
    description: "Atingir 95% de acertos em amostra mínima de 500 questões.",
    iconName: "Trophy",
    rarity: "lendaria",
    targetValue: 95,
    unit: "porcentagem",
  },

  // 6. REVISÕES
  {
    id: "REVIEWS_1",
    categoryId: "revisoes",
    title: "Primeira Retomada",
    description: "Realize sua 1ª revisão espaçada para consolidar a memória.",
    iconName: "RotateCcw",
    rarity: "comum",
    targetValue: 1,
    unit: "revisoes",
  },
  {
    id: "REVIEWS_10",
    categoryId: "revisoes",
    title: "Revisão em Dia",
    description: "Conclua 10 revisões agendadas pelo sistema.",
    iconName: "RotateCcw",
    rarity: "comum",
    targetValue: 10,
    unit: "revisoes",
  },
  {
    id: "REVIEWS_50",
    categoryId: "revisoes",
    title: "Ciclo de Fixação",
    description: "Atinja a marca de 50 revisões concluídas.",
    iconName: "RotateCcw",
    rarity: "rara",
    targetValue: 50,
    unit: "revisoes",
  },
  {
    id: "REVIEWS_100",
    categoryId: "revisoes",
    title: "Memória Consolidada",
    description: "Conclua 100 revisões de tópicos ou flashcards.",
    iconName: "BrainCircuit",
    rarity: "rara",
    targetValue: 100,
    unit: "revisoes",
  },
  {
    id: "REVIEWS_250",
    categoryId: "revisoes",
    title: "Revisão Sistemática",
    description: "Alcance 250 revisões espaçadas concluídas.",
    iconName: "BrainCircuit",
    rarity: "epica",
    targetValue: 250,
    unit: "revisoes",
  },
  {
    id: "REVIEWS_500",
    categoryId: "revisoes",
    title: "Retenção Forte",
    description: "Conclua 500 revisões mantendo seu edital na ponta da língua.",
    iconName: "Award",
    rarity: "epica",
    targetValue: 500,
    unit: "revisoes",
  },
  {
    id: "REVIEWS_1000",
    categoryId: "revisoes",
    title: "Revisão de Alto Volume",
    description: "Atinja o marco de 1.000 revisões realizadas com método.",
    iconName: "Trophy",
    rarity: "lendaria",
    targetValue: 1000,
    unit: "revisoes",
  },

  // 7. SIMULADOS
  {
    id: "SIMULADOS_1",
    categoryId: "simulados",
    title: "Primeiro Simulado",
    description: "Complete seu 1º simulado completo com controle de tempo.",
    iconName: "ClipboardCheck",
    rarity: "comum",
    targetValue: 1,
    unit: "simulados",
  },
  {
    id: "SIMULADOS_5",
    categoryId: "simulados",
    title: "Treino de Prova",
    description: "Conclua 5 simulados cronometrados.",
    iconName: "ClipboardCheck",
    rarity: "comum",
    targetValue: 5,
    unit: "simulados",
  },
  {
    id: "SIMULADOS_10",
    categoryId: "simulados",
    title: "Ritmo de Simulado",
    description: "Atinja a marca de 10 simulados realizados.",
    iconName: "Target",
    rarity: "rara",
    targetValue: 10,
    unit: "simulados",
  },
  {
    id: "SIMULADOS_25",
    categoryId: "simulados",
    title: "Série Competitiva",
    description: "Conclua 25 simulados de preparação para concurso.",
    iconName: "Target",
    rarity: "epica",
    targetValue: 25,
    unit: "simulados",
  },
  {
    id: "SIMULADOS_50",
    categoryId: "simulados",
    title: "Ambiente de Prova",
    description: "Alcance 50 simulados realizados com análise de acertos.",
    iconName: "Award",
    rarity: "epica",
    targetValue: 50,
    unit: "simulados",
  },
  {
    id: "SIMULADOS_100",
    categoryId: "simulados",
    title: "Centena de Simulados",
    description: "100 simulados concluídos com domínio de tempo de prova.",
    iconName: "Trophy",
    rarity: "lendaria",
    targetValue: 100,
    unit: "simulados",
  },

  // 8. PLANEJAMENTO & ADERÊNCIA
  {
    id: "PLAN_CREATED",
    categoryId: "planejamento",
    title: "Plano Criado",
    description: "Configure e ative seu primeiro plano de estudos.",
    iconName: "CalendarPlus",
    rarity: "comum",
    targetValue: 1,
    unit: "acao",
  },
  {
    id: "PLAN_DAY_DONE",
    categoryId: "planejamento",
    title: "Plano Executado",
    description: "Conclua um dia inteiro de estudo conforme planejado.",
    iconName: "CalendarCheck",
    rarity: "comum",
    targetValue: 1,
    unit: "acao",
  },
  {
    id: "PLAN_WEEK_DONE",
    categoryId: "planejamento",
    title: "Semana Planejada",
    description: "Conclua uma semana cumprindo as matérias planejadas.",
    iconName: "CalendarRange",
    rarity: "rara",
    targetValue: 1,
    unit: "acao",
  },
  {
    id: "PLAN_ADHERENCE_80",
    categoryId: "planejamento",
    title: "Planejamento Consistente",
    description: "Alcance 80% ou mais de aderência ao plano em uma semana.",
    iconName: "CheckCircle",
    rarity: "rara",
    targetValue: 80,
    unit: "porcentagem",
  },
  {
    id: "PLAN_ADHERENCE_90",
    categoryId: "planejamento",
    title: "Execução de Elite",
    description: "Alcance 90% ou mais de aderência semanal ao planejamento.",
    iconName: "Award",
    rarity: "epica",
    targetValue: 90,
    unit: "porcentagem",
  },
  {
    id: "PLAN_MASTER_4_WEEKS",
    categoryId: "planejamento",
    title: "Mestre da Rotina",
    description: "Mantenha 90%+ de aderência ao plano por 4 semanas consecutivas.",
    iconName: "Trophy",
    rarity: "lendaria",
    targetValue: 4,
    unit: "semanas",
  },
  {
    id: "REPLAN_FAST_RECOVERY",
    categoryId: "planejamento",
    title: "Recuperação Rápida",
    description: "Recupere uma pendência pelo sistema adaptativo sem atraso.",
    iconName: "Sparkles",
    rarity: "comum",
    targetValue: 1,
    unit: "acao",
  },
  {
    id: "REPLAN_ROUTE_TURN",
    categoryId: "planejamento",
    title: "Virada de Rota",
    description: "Recupere um dia perdido e normalize seu cronograma.",
    iconName: "Compass",
    rarity: "rara",
    targetValue: 1,
    unit: "acao",
  },

  // 9. COBERTURA DO EDITAL
  {
    id: "COVERAGE_FIRST_TOPIC",
    categoryId: "cobertura",
    title: "Primeiro Avanço",
    description: "Estude o primeiro tópico do edital verticalizado.",
    iconName: "BookOpen",
    rarity: "comum",
    targetValue: 1,
    unit: "topicos",
  },
  {
    id: "COVERAGE_25_PCT",
    categoryId: "cobertura",
    title: "25% do Conteúdo",
    description: "Estude e cubra 25% dos tópicos cadastrados do seu edital.",
    iconName: "Layers",
    rarity: "rara",
    targetValue: 25,
    unit: "porcentagem",
  },
  {
    id: "COVERAGE_50_PCT",
    categoryId: "cobertura",
    title: "Metade do Caminho",
    description: "Cubra 50% dos tópicos do seu planejamento/edital.",
    iconName: "Layers",
    rarity: "rara",
    targetValue: 50,
    unit: "porcentagem",
  },
  {
    id: "COVERAGE_75_PCT",
    categoryId: "cobertura",
    title: "Conteúdo Avançado",
    description: "Atinja 75% de cobertura dos tópicos do edital.",
    iconName: "Award",
    rarity: "epica",
    targetValue: 75,
    unit: "porcentagem",
  },
  {
    id: "COVERAGE_90_PCT",
    categoryId: "cobertura",
    title: "Edital Percorrido",
    description: "Percorra 90% de todos os tópicos previstos no edital.",
    iconName: "Award",
    rarity: "epica",
    targetValue: 90,
    unit: "porcentagem",
  },
  {
    id: "COVERAGE_100_PCT",
    categoryId: "cobertura",
    title: "Edital Mapeado (100%)",
    description: "Cubra 100% dos tópicos registrados no seu planejamento.",
    iconName: "Trophy",
    rarity: "lendaria",
    targetValue: 100,
    unit: "porcentagem",
  },

  // 10. ALTA PERFORMANCE & HORÁRIOS
  {
    id: "TIME_MORNING",
    categoryId: "alta-performance",
    title: "Sessão Matinal",
    description: "Realize pelo menos 5 sessões de estudo produtivo entre 06h e 12h.",
    iconName: "Sun",
    rarity: "comum",
    targetValue: 5,
    unit: "sessoes",
  },
  {
    id: "TIME_AFTERNOON",
    categoryId: "alta-performance",
    title: "Sessão Vespertina",
    description: "Realize pelo menos 5 sessões de estudo entre 12h e 18h.",
    iconName: "Sunset",
    rarity: "comum",
    targetValue: 5,
    unit: "sessoes",
  },
  {
    id: "TIME_NIGHT",
    categoryId: "alta-performance",
    title: "Sessão Noturna",
    description: "Realize pelo menos 5 sessões de estudo entre 18h e 22h.",
    iconName: "Moon",
    rarity: "comum",
    targetValue: 5,
    unit: "sessoes",
  },
  {
    id: "DISCIPLINE_STRONG_POINT",
    categoryId: "alta-performance",
    title: "Ponto Forte",
    description: "Alcance 85%+ de acertos em uma disciplina (mínimo de 30 questões).",
    iconName: "ShieldCheck",
    rarity: "rara",
    targetValue: 85,
    unit: "porcentagem",
  },
  {
    id: "DISCIPLINE_SPECIALIST",
    categoryId: "alta-performance",
    title: "Especialista na Matéria",
    description: "Alcance 90%+ de acertos em uma disciplina (mínimo de 50 questões).",
    iconName: "Award",
    rarity: "epica",
    targetValue: 90,
    unit: "porcentagem",
  },
  {
    id: "PERFORMANCE_APPROVAL_RANGE",
    categoryId: "alta-performance",
    title: "Faixa de Aprovação",
    description: "Alcance 90%+ de aproveitamento médio em simulados válidos.",
    iconName: "Trophy",
    rarity: "lendaria",
    targetValue: 90,
    unit: "porcentagem",
  },
]
